# This file is generate by https://github.com/nearform/k8s-kurated-addons-cli
name: Build and Push

on: 
  push:
    branches:
      - main

jobs:
  cli:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/heidermassu/heidermassu/js-app-01/js-app-01:v1.1
    steps:
      - name: build docker image application
        run: build sleep infinity
      
      - name: push docker image application
        run: push
        env:
          KKA_REGISTRY_USER: ${{ github.actor }}
          KKA_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      
     